import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { TabsContent } from "@/components/ui/tabs";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Download, FileText } from "lucide-react";
import { ReportTypesEnum, type TReportTypes } from "@/constants/defaults";
import { inventoryReports } from "@/assets/data";

type Props = {
  handleOpenGenerateDialog: (type: TReportTypes) => void;
  handleViewReport: (report: any) => void;
  handleDownloadReport: (reportName: string) => void;
};

const InventoryTab = ({
  handleOpenGenerateDialog,
  handleViewReport,
  handleDownloadReport,
}: Props) => {
  return (
    <TabsContent value={ReportTypesEnum.INVENTORY.value} className="space-y-6">
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Inventory Reports</CardTitle>
              <CardDescription>
                Stock levels, consumption analysis, and inventory tracking
              </CardDescription>
            </div>
            <Button
              onClick={() =>
                handleOpenGenerateDialog(ReportTypesEnum.INVENTORY.value)
              }
              className="bg-blue-600 hover:bg-blue-700"
            >
              <FileText className="mr-2 size-4" />
              Generate Report
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Report Name</TableHead>
                <TableHead>Type</TableHead>
                <TableHead>Project</TableHead>
                <TableHead>Total Items</TableHead>
                <TableHead>Low Stock Items</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Date</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {inventoryReports.map((report) => (
                <TableRow key={report.id}>
                  <TableCell className="font-medium">{report.name}</TableCell>
                  <TableCell>{report.type}</TableCell>
                  <TableCell>{report.project}</TableCell>
                  <TableCell>{report.totalItems}</TableCell>
                  <TableCell>
                    <span
                      className={
                        report.lowStock > 10
                          ? "font-medium text-red-600"
                          : "text-green-600"
                      }
                    >
                      {report.lowStock}
                    </span>
                  </TableCell>
                  <TableCell>{report.generatedBy}</TableCell>
                  <TableCell>{report.date}</TableCell>
                  <TableCell>
                    <div className="flex gap-2">
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleViewReport(report)}
                      >
                        View
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleDownloadReport(report.name)}
                      >
                        <Download className="size-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </TabsContent>
  );
};

export default InventoryTab;
