import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { TabsContent } from "@/components/ui/tabs";
import {
  Table,
  // TableBody,
  // TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import {
  // Download,
  FileText,
} from "lucide-react";
import { ReportTypesEnum, type TReportTypes } from "@/constants/defaults";
// import { salesReports } from "@/assets/data";

type Props = {
  handleOpenGenerateDialog: (type: TReportTypes) => void;
  handleViewReport: (report: any) => void;
  handleDownloadReport: (reportName: string) => void;
};

const SalesTab = ({
  handleOpenGenerateDialog,
  // handleViewReport,
  // handleDownloadReport,
}: Props) => {
  return (
    <TabsContent value={ReportTypesEnum.SALES.value} className="space-y-6">
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Sales Reports</CardTitle>
              <CardDescription>
                Unit sales, performance metrics, and sales analysis
              </CardDescription>
            </div>
            <Button
              onClick={() =>
                handleOpenGenerateDialog(ReportTypesEnum.SALES.value)
              }
              className="bg-blue-600 hover:bg-blue-700"
            >
              <FileText className="mr-2 size-4" />
              Generate Report
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Report Name</TableHead>
                <TableHead>Type</TableHead>
                <TableHead>Project</TableHead>
                <TableHead>Units Total</TableHead>
                <TableHead>Units Sold</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Date</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            {/* <TableBody>
              {salesReports.map((report) => (
                <TableRow key={report.id}>
                  <TableCell className="font-medium">{report.name}</TableCell>
                  <TableCell>{report.type}</TableCell>
                  <TableCell>{report.project}</TableCell>
                  <TableCell>{report.unitsTotal}</TableCell>
                  <TableCell>{report.unitsSold}</TableCell>
                  <TableCell>{report.generatedBy}</TableCell>
                  <TableCell>{report.date}</TableCell>
                  <TableCell>
                    <div className="flex gap-2">
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleViewReport(report)}
                      >
                        View
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleDownloadReport(report.name)}
                      >
                        <Download className="size-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody> */}
          </Table>
        </CardContent>
      </Card>
    </TabsContent>
  );
};

export default SalesTab;
